language: node_js
sudo: false
node_js:
  - '4.2.3'
branches:
  only:
    - master
env:
  global:
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
before_script:
  - ./scripts/ci/build-and-test.sh
script:
  - npm run test
