language: node_js
sudo: false
node_js:
  - '4.2.3'
branches:
  only:
    - master
env:
  global:
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - CXX=g++-4.8
before_script:
  # Necessary to run test on Travis CI that require a graphical interface.
  # See https://docs.travis-ci.com/user/gui-and-headless-browsers
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh
cache:
  directories:
    - node_modules
