language: node_js
sudo: false

node_js:
  - '5.6.0'

branches:
  only:
    - master

env:
  global:
  - LOGS_DIR=/tmp/visualdiff-dev/logs
  - SAUCE_READYFILE=/tmp/visualdiff-dev/sauce-connect-ready-$RANDOM
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/build-and-test.sh
